Make apache5-client the default sync HTTP client (#6732)
* Swap apache-client with apache5-client

This commit swaps the default apache-client dependency of service
modules with apache5-client. Applications just relying on the default
HTTP client will now use `Apache5HttpClient` as a result.

* Fix CloudFrontUtilitiesIntegrationTest

* Fix S3 tests

* Update version in changelog entry

* Revert to 4.x for test

Expect100ContinueHeaderTest tests 4.x specific behavior (default
100-continue).

* Add apache-client to aws-sdk-java module to prevent NoClassDefFoundError for customers using ApacheHttpClient in environments that bundle the whole SDK (e.g., EMR) after apache5-client default switch (#6964)

* fix(integ-test): Fix Integ test issue after making Apache5 as default (#6974)

* fix(dynamodb): Add TCP keep-alive permissions to SecurityManager test policy for Apache 5 compatibility. Apache 5.6 sets TCP_KEEPIDLE/INTERVAL/COUNT by default which requires jdk.net.NetworkPermission.

* Fix ResponseInputStreamTimeoutIntegrationTest to update it to Apache5 exception assertion

* Remove apache5-client test scope from s3/pom.xml to restore runtime transitivity. The test scope override prevented downstream modules like s3-transfer-manager from discovering the HTTP client via SPI

* Dumy commit to trigger integ test

* because we use  org.apache.hc.core5.http.ConnectionRequestTimeoutException in ResponseInputStreamTimeoutIntegrationTest

* Removing Apache5 specific execption from ResponseInputStreamTimeoutIntegrationTest and asserting just on error message

* remove apache 5 as test dependency since it present as runtime

* Updated change logs to have notable changes in the change logs

* Upgrade httpcomponents.client5 to 5.6.1

---------

Co-authored-by: John Viegas <70235430+joviegas@users.noreply.github.com>
Co-authored-by: John Viegas <joviegas@amazon.com>